blogSite/author/urls.py
from django.urls import path
from .views import LoginView, SignupView, LogOutView, AuthorList, ProfileView, ActivateView

app_name = 'author'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('all/', AuthorList.as_view(), name='authors'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
]

blogSite/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.BlogsList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.BlogsDetail.as_view(), name='detail'),
    path('create/', views.BlogsCreate.as_view(), name='create'),
    path('update/<slug:slug>/', views.BlogsUpdate.as_view(), name='update'),
    path('delete/<slug:slug>/confirm', views.BlogsDelete.as_view(), name='delete'),
]

blogSite/blogSite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/', include('author.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogSite/author/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    bio = models.CharField(max_length=200, null=True, blank=True)
    occupation = models.CharField(max_length=100, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

blogSite/author/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

from .models import Author


class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        required = ['first_name', 'last_name']


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        exclude = ['user']

blogSite/author/views.py
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage

from .forms import CreateUserForm, AuthorForm
from .models import Author
from .tokens import account_activation_token


class SignupView(View):
    form = CreateUserForm()
    template_name = 'author/signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/blog/')
        else:
            form = self.form
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            username = form.cleaned_data.get('first_name')
            Author.objects.create(
                user=user,
                name=user.first_name + " " + user.last_name,
            )
            current_site = get_current_site(request)
            mail_subject = 'Activate your BlogSite account.'
            message = render_to_string('author/activate.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            print(urlsafe_base64_encode(force_bytes(user.pk)),
                  account_activation_token.make_token(user))
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(
                request,
                "  Successfully SignUp! Please activate your account mail has been send to your mail box! ")
            messages.success(request, 'Account created successfully for ' + username)
            return HttpResponseRedirect('/author/login/')

        return render(request, self.template_name, {'form': form})


class LoginView(View):
    template_name = 'author/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/blog/')
        else:
            return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect('/blog/')
        else:
            messages.error(request, 'Username or password is incorrect.')

        return render(request, self.template_name)


@method_decorator(login_required(login_url='/author/login'), name='get')
class LogOutView(View):
    template_name = 'author/login.html'

    def get(self, request):
        logout(request)
        return render(request, self.template_name)


@method_decorator(login_required(login_url='/author/login'), name='get')
class ProfileView(View):
    template_name = 'author/profile.html'

    def get(self, request):
        user = request.user.author
        form = AuthorForm(instance=user)
        # blogs = request.user.author.blogarticle_set.all()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user = request.user.author
        form = AuthorForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/author/profile/')

        return render(request, self.template_name, {'form': form})


class AuthorList(ListView):
    model = Author
    context_object_name = 'authors'
    template_name = 'blog/authors.html'
    paginate_by = 3


class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "  Thank you for your email confirmation. Now you can login to your account.")
            return redirect('author:login')

        else:
            messages.error(request, "   Activation link is invalid!.", fail_silently=True)
            return redirect('author:login')

blogSite/templates/author/activate.html
{% autoescape off %} Hi {{ user.first_name }}, Please click on the link to confirm
your account registration, http://{{ domain }}/author/activate/{{uid}}/{{token}}/
<br/>
{% endautoescape %}

blogSite/templates/author/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Author Log In </h3>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        {% block sidebar %}
        <div class="col-md-3 float-right ">
            <div class="card my-4">
                <div class="card-body">
                    <a href="{% url 'blog:home' %}" class="btn btn-danger">All Blogs</a>
                    <br><br>
                    <a href="{% url 'author:signup' %}" class="btn btn-warning">Create Account</a>
                </div>
            </div>
        </div>
        {% endblock sidebar %}

        <div class="col-md-7 mt-3 float-left">

            <form method="post" action="#">
                {% csrf_token %}
                <div class="login-form">
                    <div id="div_id_username" class="form-group">
                        <label for="username" class="requiredField">Email</label>
                        <input type="text" name="username" maxlength="150" autofocus
                               class="form-control" required id="username">
                        <label for="password" class="requiredField">Password</label>
                        <input type="password" name="password" class="form-control" required
                               id="password">
                    </div>
                    {% for message in messages %}
                    <p>{{message}}</p>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Log In</button>
            </form>
        </div>
    </div>

</div>
{%endblock%}

blogSite/templates/author/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Author Profile </h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body">
                {% if request.user.author.profile_image %}
                <img class="profile-pic" src="{{request.user.author.profile_image.url}}">
                {% else %}
                <img class="profile-pic" src="/images/default.png">
                {% endif %}

            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body">

                <form method="POST" action="#" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}

                    <input class="btn btn-primary" type="submit" value="Update Information">
                    <a href="{% url 'blog:create' %}" class="btn btn-success">Create New Blog</a>
                    <a class="btn btn-warning" href="{% url 'blog:home' %}"> &#8592; Back to Home</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% block sidebar %} {% endblock sidebar %}
</div>

</div>


{%endblock%}

blogSite/templates/author/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Author Sign Up </h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">

            <form method="post" action="/author/signup/">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Sign Up</button>
                <button type="reset" class="btn btn-danger">Reset</button>
            </form>

        </div>
        {% block sidebar %}
        <div class="col-md-3 float-right ">
            <div class="card my-4">
                <div class="card-body">
                    <a href="{% url 'blog:home' %}" class="btn btn-danger">All Blogs</a>
                    <br><br>
                    <a href="{% url 'author:login' %}" class="btn btn-primary">Sign In</a>
                </div>
            </div>
        </div>
        {% endblock sidebar %}
    </div>

</div>
{%endblock%}