blogSite/author/urls.py
from django.urls import path
from .views import LoginView, SignupView, LogOutView, AuthorList, ProfileView, ActivateView

app_name = 'author'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('all/', AuthorList.as_view(), name='authors'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
]

blogSite/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.BlogsList.as_view(), name='home'),
    path('detail/<slug:slug>/', views.BlogsDetail.as_view(), name='detail'),
    path('create/', views.BlogsCreate.as_view(), name='create'),
    path('update/<slug:slug>/', views.BlogsUpdate.as_view(), name='update'),
    path('delete/<slug:slug>/confirm', views.BlogsDelete.as_view(), name='delete'),
]

blogSite/blogSite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/', include('author.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogSite/author/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    bio = models.CharField(max_length=200, null=True, blank=True)
    occupation = models.CharField(max_length=100, null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

blogSite/blog/models.py
from django.db import models
from django.urls import reverse


class BlogArticle(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey('author.Author', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

blogSite/author/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

from .models import Author


class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        required = ['first_name', 'last_name']


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'
        exclude = ['user']

blogSite/blog/forms.py
from django import forms
from .models import BlogArticle


class CreateBlogForm(forms.ModelForm):
    class Meta:
        model = BlogArticle
        fields = ['title', 'content']

blogSite/author/views.py
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import View, ListView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage

from .forms import CreateUserForm, AuthorForm
from .models import Author
from .tokens import account_activation_token


class SignupView(View):
    form = CreateUserForm()
    template_name = 'author/signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/blog/')
        else:
            form = self.form
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            username = form.cleaned_data.get('first_name')
            Author.objects.create(
                user=user,
                name=user.first_name + " " + user.last_name,
            )
            current_site = get_current_site(request)
            mail_subject = 'Activate your BlogSite account.'
            message = render_to_string('author/activate.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            print(urlsafe_base64_encode(force_bytes(user.pk)),
                  account_activation_token.make_token(user))
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(
                request,
                "  Successfully SignUp! Please activate your account mail has been send to your mail box! ")
            messages.success(request, 'Account created successfully for ' + username)
            return HttpResponseRedirect('/author/login/')

        return render(request, self.template_name, {'form': form})


class LoginView(View):
    template_name = 'author/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/blog/')
        else:
            return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect('/blog/')
        else:
            messages.error(request, 'Username or password is incorrect.')

        return render(request, self.template_name)


@method_decorator(login_required(login_url='/author/login'), name='get')
class LogOutView(View):
    template_name = 'author/login.html'

    def get(self, request):
        logout(request)
        return render(request, self.template_name)


@method_decorator(login_required(login_url='/author/login'), name='get')
class ProfileView(View):
    template_name = 'author/profile.html'

    def get(self, request):
        user = request.user.author
        form = AuthorForm(instance=user)
        # blogs = request.user.author.blogarticle_set.all()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user = request.user.author
        form = AuthorForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/author/profile/')

        return render(request, self.template_name, {'form': form})


class AuthorList(ListView):
    model = Author
    context_object_name = 'authors'
    template_name = 'blog/authors.html'
    paginate_by = 3


class ActivateView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, "  Thank you for your email confirmation. Now you can login to your account.")
            return redirect('author:login')

        else:
            messages.error(request, "   Activation link is invalid!.", fail_silently=True)
            return redirect('author:login')

blogSite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from .models import BlogArticle
from .forms import CreateBlogForm


class BlogsList(ListView):
    queryset = BlogArticle.objects.all().order_by('-created_at')
    context_object_name = 'blogs'
    template_name = 'blog/allblogs.html'
    paginate_by = 3


class BlogsDetail(DetailView):
    model = BlogArticle
    pk_url_kwarg = 'id'
    context_object_name = 'blog'
    template_name = 'blog/blog_detail.html'


def create_slug(string):
    s = string.lower()
    words = s.split(' ')
    slug = '-'.join(words)
    return slug


@method_decorator(login_required, name='dispatch')
class BlogsCreate(CreateView):
    form_class = CreateBlogForm
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user.author
        form.instance.slug = create_slug(form.cleaned_data['title'])
        form.save()
        form.save_m2m()
        return super(BlogsCreate, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class BlogsUpdate(UserPassesTestMixin, UpdateView):
    model = BlogArticle
    pk_url_kwarg = 'id'
    form_class = CreateBlogForm
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.author = self.request.user.author
        form.instance.slug = create_slug(form.cleaned_data['title'])
        form.save()
        form.save_m2m()
        return super(BlogsUpdate, self).form_valid(form)

    def test_func(self):
        article = self.get_object()
        if self.request.user.author == article.author:
            return True
        return False


@method_decorator(login_required, name='dispatch')
class BlogsDelete(UserPassesTestMixin, DeleteView):
    model = BlogArticle
    pk_url_kwarg = 'id'
    context_object_name = 'blog'
    template_name = 'blog/delete.html'
    success_url = '/blog/'

    def test_func(self):
        article = self.get_object()
        if self.request.user.author == article.author:
            return True
        return False

blogSite/templates/blog/allblogs.html
{% extends 'blog/base.html' %}
{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Simple Django Blog App </h3>
                    <p class="text-light">Share your knowledge with the world. &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% if not blogs %}
            There are no blogs to display. Write one using django-admin.
            {% endif %}

            {% for blog in blogs %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="col-md-2" style="float:left">
                        {% if blog.author.profile_image %}
                        <img class="profile-pic-blog" src="{{blog.author.profile_image.url}}">
                        {% else %}
                        <img class="profile-pic-blog" src="/images/default.png">
                        {% endif %}
                    </div>

                    <div class="col-md-9">
                        <h2 class="card-title">{{ blog.title }}</h2>
                        <p class="card-text text-muted h6">{{ blog.author }} | {{ blog.created_at}} </p>
                        <p class="card-text">{{blog.content|slice:":200" }}</p>
                        {% if blog.author == request.user.author %}
                        <a href="{% url 'blog:update' blog.slug %}" class="btn btn-warning">Update</a>
                        <a href="{% url 'blog:delete' blog.slug %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                        <a href="{% url 'blog:detail' blog.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation conatiner"></nav>
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
</ul>
</nav>
</div>
{% endif %}
{%endblock%}

blogSite/templates/blog/authors.html
{% extends 'blog/base.html' %}
{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Simple Django Blog App </h3>
                    <p class="text-light">Share your knowledge with the world. &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% if not authors %}
            There are no authors to display. Create one using django admin.
            {% endif %}

            {% for author in authors %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ author.name }}</h2>
                    <p class="card-text text-muted h6">{{ author.username }} | {{ author.email}} </p>
                    <p class="card-text">{{author.bio|slice:":200" }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %}
        <div class="col-md-4 float-right ">
            <div class="card my-4">
                <div class="card-body">
                    <a href="{% url 'blog:home' %}" class="btn btn-danger">Back to All Blogs</a>
                </div>
            </div>
        </div>
        {% endblock sidebar %}
    </div>
</div>
{% if is_paginated %}
<nav aria-label="Page navigation conatiner"></nav>
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
</ul>
</nav>
</div>
{% endif %}
{%endblock%}

blogSite/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Blogs Site</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Blogs Site</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {% if not request.user or request.user.is_anonymous %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'author:login' %}">Log In</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'author:profile' %}">{{request.user}}</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'author:logout' %}">Logout</a>
                </li>
            </ul>
            {% endif %}

        </div>
    </div>
</nav>
{% block content %}
<!-- Content Goes here -->
{% endblock content %}

<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; Blogs Site</p>
</footer>
</body>
</html>

blogSite/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 left  top">
            <div class="card-body">
                <div class="col-md-2" style="float:left">
                    {% if blog.author.profile_image %}
                    <img class="profile-pic-blog" src="{{blog.author.profile_image.url}}">
                    {% else %}
                    <img class="profile-pic-blog" src="/images/default.png">
                    {% endif %}
                </div>
                <div class="col-md-9">
                    <h1>{% block title %} {{ blog.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ blog.author }} | {{ blog.created_at }}</p>
                    {% if not blog.updated_at == blog.created_at %}
                    <p class=" text-muted">Edited at: {{ blog.updated_at }}</p>
                    {% endif %}
                    <p class="card-text ">{{ blog.content | safe }}</p>
                    {% if blog.author == request.user.author %}
                    <a href="{% url 'blog:update' blog.slug %}" class="btn btn-warning">Update</a>
                    <a href="{% url 'blog:delete' blog.slug %}" class="btn btn-danger">Delete</a>
                    {% endif %}
                    <a href="{% url 'blog:home' %}" class="btn btn-primary">Back to Home &rarr;</a>
                </div>
            </div>
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>

{% endblock content %}

blogSite/templates/blog/create.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Blog
                        {% if 'update' in request.get_full_path %}
                        Update
                        {% elif 'create' in request.get_full_path %}
                        Create
                        {% endif %} </h3>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">

            <form method="post" action="#">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-success">
                    {% if 'update' in request.get_full_path %}
                    Update
                    {% elif 'create' in request.get_full_path %}
                    Create
                    {% endif %}
                </button>
                <button type="reset" class="btn btn-danger">Reset</button>
            </form>

        </div>
        {% block sidebar %}
        <div class="col-md-4 float-right ">
            <div class="card my-4">
                <h5 class="card-header">Quick Links</h5>
                <div class="card-body">
                    <a href="{% url 'author:authors' %}" class="btn btn-danger">All Authors</a>
                    <a href="{% url 'blog:home' %}" class="btn btn-primary">All Blogs</a>
                </div>
            </div>
        </div>
        {% endblock sidebar %}
    </div>

</div>
{%endblock%}

blogSite/templates/blog/delete.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Blog Delete
                        <h4>Are you sure you want to delete the blog "{{blog.title}}"?</h4>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">

            <form method="post" action="#">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Yes, Delete.</button>
                <a class="btn btn-secondary" href="{% url 'blog:detail' blog.slug %}">Cancel</a>
            </form>

        </div>
        {% block sidebar %} {% endblock sidebar %}
    </div>

</div>
{%endblock%}

blogSite/templates/blog/sidebar.html
{% block sidebar %}

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
        <h5 class="card-header">Quick Links</h5>
        <div class="card-body">
            <a href="{% url 'author:authors' %}" class="btn btn-danger">All authors</a>
            <a href="{% url 'blog:create' %}" class="btn btn-success">Create New Blog</a>
        </div>
    </div>
</div>

{% endblock sidebar %}